apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: blinkt
  labels:
    app: blinkt
    version: v1
spec:
  template:
    metadata:
      labels:
        name: blinkt
    spec:
      containers:
          - name: blinkt
          - securityContext:
              privileged: true
          - image: alexellis2/progress-blinkt:red          